name: CDA-Viewer deployment - Prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [windows-2019]
        architecture: [x64]
    
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Docker login
      #   uses: docker/login-action@v1
      #   with:
      #     registry: https://${{ secrets.registry }}.azurecr.io
      #     username: ${{ secrets.service_principal }}
      #     password: ${{ secrets.service_principal_password }}

      # - name: Docker build and push
      #   run: |
      #     docker build -t ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/cda-viewer:${{ github.sha }} -f ./app/Dockerfile ./app
      #     docker push ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/cda-viewer:${{ github.sha }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-artifacts
          path: |
            app
            cda-viewer

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: built-artifacts

      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.resource_group }}'
          cluster-name: '${{ secrets.cluster_name }}'

      - name: Set up Helm
        run: |
          echo "Helm version: $(helm version --short)"
          echo "Helm home: $HOME\.helm"
          echo "Helm path: $(where.exe helm)"

      # - name: Extract Helm chart
      #   run: |
      #     tar -zxvf ./cda-viewer.tar.gz -C ./cda-viewer

      - name: Deploy Helm chart
        run: |
          & $(where.exe helm) upgrade --install "***-chart" ./path/to/chart --atomic --namespace ***-self `
          --set image.repository=***.azurecr.io/***/***,image.tag=${{ github.sha }} `
          --atomic --set changeCause=${{ github.sha }}


