name: CDA-Viewer deployment - Prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [linux]
        architecture: [x64]
    
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          image: ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/cda-viewer:${{ github.sha }}
          context: ./app
          dockerfile: ./app/Dockerfile
          repository-name: ${{ secrets.repository }}
          repository-tag: ${{ github.sha }}
          build-args: ""

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-artifacts
          path: cda-viewer


  # deploy:
  #   needs: build
  #   runs-on: self-hosted

  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: built-artifacts

  #     - name: Azure login
  #       uses: azure/login@v1.4.3
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: Set AKS context
  #       id: set-context
  #       uses: azure/aks-set-context@v3
  #       with:
  #         resource-group: '${{ secrets.resource_group }}' 
  #         cluster-name: '${{ secrets.cluster_name }}'

  #     - name: Helm tool installer
  #       uses: Azure/setup-helm@v3
  #       with:
  #         version: 3.6.0

  #     - name: Deploy Helm chart
  #       run: |
  #         helm upgrade --install cda-viewer cda-viewer/ --atomic --namespace cda-viewer-ns `
  #         --set image.repository=${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/cda-viewer,image.tag=${{ github.sha }} `
  #         --atomic --set changeCause=${{ github.sha }}


