name: CDA-Viewer deployment - Prod
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  
    
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - name: Azure login
        id: azure-login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/cda-viewer:${{ github.sha }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-artifacts
          path: |
            app
            cda-viewer

  deploy:
    needs: build
    runs-on: self-hosted  

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: built-artifacts
          
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.resource_group }}' 
          cluster-name: '${{ secrets.cluster_name }}'

      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:
          version: 3.6.0

      - name: Deploy Helm chart
        run: |
          helm upgrade --install "cda-viewer-chart" cda-viewer/ --atomic --namespace cda-viewer-self \
            --set image.repository=${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/cda-viewer,image.tag=${{ github.sha }} \
            --atomic --set changeCause=${{ github.sha }}
